# config file for running 10x pipeline 

DATA:
    "../runs/tmp"

PROJECT:
    "Collins"

TRANSCRIPTOME:
    "/vol3/home/riemondy/Projects/shared_dbases/cell_ranger/refdata-cellranger-mm10-1.2.0"

SAMPLES:
    - Collins_TNF_deltaARE
    - Collins_WT 

EXPT_GROUPS:
    - Collins_TNF_deltaARE 

MAX_10X_JOBS:
    30
