# config file for running 10x pipeline 

RUN: 
    "../runs/10xpilot2/170418_K00262_0090_BHJJG5BBXX/"

DATA:
    "../runs/10xpilot2"

SPECIES: 
    "human"

SAMPLE_SHEET: 
    "../runs/10xpilot2/docs/10x_samplesheet_illuminastyle.csv"

PROJECT: 
    "10xPilot2"

TRANSCRIPTOME:
    "~/Projects/shared_dbases/cell_ranger/refdata-cellranger-GRCh38-1.2.0/"

SAMPLES:
    - AML1
    - AML2
    - AML3 
    - AW1
    - AW2
    - AW3
    - PK65BRAIN2
    - PT46LIVER4
    - PT46TUMOR3
    - PK65TUMOR1

INDICIES:
    - SI-GA-H5
    - SI-GA-G5
    - SI-GA-F5
    - SI-GA-A5
    - SI-GA-H6
    - SI-GA-G6
    - SI-GA-D5
    - SI-GA-B5
    - SI-GA-C5
    - SI-GA-E5

LANES: "5,6,7,8"

EXPT_GROUPS:
    - AML1,AML2,AML3
    - AW1,AW2,AW3
    - PK65TUMOR1,PK65BRAIN2,PT46LIVER4,PT46TUMOR3 
