# config file for running 10x pipeline 

DATA:
    "../runs/tmp"
PROJECT:
    "zemans"

TRANSCRIPTOME:
    "/vol3/home/riemondy/Projects/shared_dbases/cell_ranger/refdata-cellranger-mm10-1.2.0"

SAMPLE_SHEET: 
    "../runs/tmp/docs/samples.txt"

SAMPLES:
    - Collins_TNF_deltaARE
    - Collins_WT 

EXPT_GROUPS:
    - Collins_TNF_deltaARE,Collins_WT 

MAX_10X_JOBS:
    30
