# config file for running 10x pipeline 

DATA:
    "../runs/20170728_zeeman_expt2"

PROJECT:
    "zeemans_run2"

TRANSCRIPTOME:
    "~/Projects/shared_dbases/cell_ranger/refdata-cellranger-mm10-1.2.0/"    

SAMPLE_SHEET: 
    "../runs/20170728_zeeman_expt2/docs/samples.txt"

SAMPLES:
    - "3242ATI1"
    - "3242ATI2"
    - "3242ATII3"
    - "3241ATII4"
    - "3241ATII5"

EXPT_GROUPS:
    - 3241ATII4,3241ATII5,3242ATI1,3242ATI2,3242ATII3 
